services:
  appuser_microservice_db:
    container_name: 'appuser_microservice_db'
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=imagecatalogue
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
  appuser_microservice:
    build: .
    container_name: 'appuser_microservice'
    ports:
      - 8081:8080
    environment:
      - DB_HOSTNAME=appuser_microservice_db
      - DB_PORT=3306
    depends_on:
      appuser_microservice_db:
        condition: service_healthy
        restart: true